-- Seed additional job listings for a fuller jobs page
INSERT INTO jobs (title, description, location, facility_name, employment_type, min_experience_years, required_certifications, required_skills, salary_min, salary_max, salary_currency, is_active)
VALUES
  (
    'Emergency Room Nurse',
    'Fast-paced ER environment seeking skilled nurses who can perform triage, manage trauma cases, and coordinate with multidisciplinary teams. Must remain calm under pressure and prioritize effectively in high-acuity situations.',
    'Manila, Philippines',
    'The Medical City',
    'full-time',
    3,
    ARRAY['PRC License'],
    ARRAY['Emergency Response', 'Triage', 'IV Therapy', 'Wound Care', 'Critical Care'],
    42000,
    55000,
    'PHP',
    true
  ),
  (
    'Pediatric Nurse',
    'Caring for infants, children, and adolescents in our pediatric ward. Responsibilities include growth monitoring, immunization administration, family education, and age-appropriate care delivery.',
    'Davao City, Philippines',
    'Southern Philippines Medical Center',
    'full-time',
    2,
    ARRAY['PRC License'],
    ARRAY['Pediatric Care', 'Immunization', 'Patient Education', 'Vital Signs Monitoring', 'Medication Administration'],
    32000,
    42000,
    'PHP',
    true
  ),
  (
    'Dialysis Nurse',
    'Specialized nurse for our hemodialysis unit. Will manage dialysis machines, monitor patients during treatment, assess vascular access sites, and educate patients on renal diet and fluid management.',
    'Pasig City, Philippines',
    'National Kidney and Transplant Institute',
    'full-time',
    2,
    ARRAY['PRC License'],
    ARRAY['Hemodialysis', 'Patient Assessment', 'Vital Signs Monitoring', 'Infection Control', 'Patient Education'],
    40000,
    52000,
    'PHP',
    true
  ),
  (
    'Nurse Supervisor - Surgical Ward',
    'Leadership role overseeing daily operations of the surgical ward. Manage a team of 15 nurses, coordinate patient flow, ensure quality standards, and mentor junior staff.',
    'Quezon City, Philippines',
    'Philippine General Hospital',
    'full-time',
    5,
    ARRAY['PRC License', 'NCLEX'],
    ARRAY['Leadership', 'Care Planning', 'Clinical Documentation', 'Perioperative Nursing', 'Mentorship'],
    55000,
    72000,
    'PHP',
    true
  ),
  (
    'Oncology Nurse',
    'Join our cancer care team administering chemotherapy, managing side effects, and providing compassionate support to patients and families throughout their treatment journey.',
    'Manila, Philippines',
    'Philippine Cancer Center',
    'full-time',
    3,
    ARRAY['PRC License'],
    ARRAY['Chemotherapy Administration', 'IV Therapy', 'Patient Education', 'Pain Management', 'Medication Administration'],
    45000,
    58000,
    'PHP',
    true
  ),
  (
    'Registered Nurse - Singapore',
    'Exciting opportunity at a leading Singapore hospital. Comprehensive benefits including housing allowance, annual flights home, and professional development funding.',
    'Singapore',
    'Mount Elizabeth Hospital',
    'contract',
    3,
    ARRAY['PRC License', 'NCLEX', 'IELTS'],
    ARRAY['Patient Assessment', 'Medication Administration', 'Critical Care', 'Clinical Documentation', 'Infection Control'],
    3500,
    5000,
    'SGD',
    true
  ),
  (
    'School Nurse',
    'Provide health services to students and staff at an international school. Includes first aid, health screening, immunization tracking, and health education programs.',
    'Taguig, Philippines',
    'International School Manila',
    'full-time',
    1,
    ARRAY['PRC License'],
    ARRAY['First Aid', 'Patient Education', 'Vital Signs Monitoring', 'Documentation', 'Immunization'],
    30000,
    38000,
    'PHP',
    true
  ),
  (
    'Neonatal ICU Nurse',
    'Specialized care for critically ill newborns in our Level III NICU. Must be proficient in neonatal resuscitation, incubator management, and family-centered care approaches.',
    'Cebu City, Philippines',
    'Chong Hua Hospital',
    'full-time',
    3,
    ARRAY['PRC License'],
    ARRAY['Neonatal Care', 'Critical Care', 'Ventilator Management', 'Patient Assessment', 'IV Therapy'],
    44000,
    58000,
    'PHP',
    true
  ),
  (
    'Registered Nurse - Canada',
    'Ontario hospital recruiting Filipino nurses. Permanent residency pathway available. Full relocation support and orientation program provided.',
    'Toronto, Canada',
    'Toronto General Hospital',
    'full-time',
    2,
    ARRAY['PRC License', 'NCLEX', 'IELTS'],
    ARRAY['Patient Assessment', 'Care Planning', 'Medication Administration', 'Clinical Documentation', 'Patient Education'],
    4200,
    5500,
    'CAD',
    true
  ),
  (
    'Occupational Health Nurse',
    'Corporate wellness and occupational health role for a major BPO company. Conduct health assessments, manage workplace injuries, and implement wellness programs for 2,000+ employees.',
    'Makati, Philippines',
    'Accenture Philippines',
    'full-time',
    2,
    ARRAY['PRC License'],
    ARRAY['Patient Assessment', 'First Aid', 'Documentation', 'Patient Education', 'Vital Signs Monitoring'],
    35000,
    45000,
    'PHP',
    true
  ),
  (
    'Travel Nurse - Rural Assignment',
    'Short-term assignment in a rural community health center. Provide primary care, immunizations, and health education to underserved communities. Housing provided.',
    'Palawan, Philippines',
    'DOH Rural Health Program',
    'contract',
    1,
    ARRAY['PRC License'],
    ARRAY['Patient Assessment', 'Immunization', 'Wound Care', 'Patient Education', 'First Aid'],
    28000,
    35000,
    'PHP',
    true
  ),
  (
    'Cardiac Catheterization Lab Nurse',
    'Assist cardiologists during diagnostic and interventional cardiac procedures. Monitor hemodynamics, administer conscious sedation, and manage post-procedure recovery.',
    'Manila, Philippines',
    'Philippine Heart Center',
    'full-time',
    3,
    ARRAY['PRC License', 'NCLEX'],
    ARRAY['Hemodynamic Monitoring', 'Critical Care', 'Sterile Technique', 'Emergency Response', 'IV Therapy'],
    48000,
    62000,
    'PHP',
    true
  ),
  (
    'Nurse Educator',
    'Develop and deliver training programs for nursing staff. Create competency assessments, conduct skills workshops, and ensure compliance with evidence-based practice standards.',
    'Quezon City, Philippines',
    'University of the Philippines - Manila',
    'full-time',
    5,
    ARRAY['PRC License', 'NCLEX'],
    ARRAY['Mentorship', 'Clinical Documentation', 'Patient Education', 'Care Planning', 'Leadership'],
    50000,
    65000,
    'PHP',
    true
  ),
  (
    'Registered Nurse - Australia',
    'Melbourne hospital seeking experienced nurses. Sponsorship visa provided. Work-life balance focused culture with excellent nurse-to-patient ratios.',
    'Melbourne, Australia',
    'Royal Melbourne Hospital',
    'full-time',
    3,
    ARRAY['PRC License', 'NCLEX', 'IELTS'],
    ARRAY['Patient Assessment', 'Critical Care', 'Medication Administration', 'Care Planning', 'Infection Control'],
    5500,
    7500,
    'AUD',
    true
  );
